# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:  
      - name: Set up Elixir
        uses: actions/checkout@v4
        
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '28.0'
          
      - name: Install dependencies
        run: mix deps.get
        
      - name: Run tests
        run: mix test
        
      - name: Build
        run: |
          export MIX_ENV=prod
          mix compile
          mix release
          
      - name: Copy artifact
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: _build/prod/rel/qlc_digital/bin/qlc_digital
          target: /tmp
        

      
